# -*- coding: utf-8 -*-
"""LCP Solver

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AnkpQKya3gQspqkqopuOhOoHQa6Ahryz

LCPSolve(M, q): procedure to solve the linear complementarity problem:

       w = M z + q
       w and z >= 0
       w'z = 0

   The procedure takes the matrix M and vector q as arguments.  The
   procedure has three returns.  The first and second returns are
   the final values of the vectors w and z found by complementary
   pivoting.  The third return is a 2 by 1 vector.  Its first
   component is a 1 if the algorithm was successful, and a 2 if a
   ray termination resulted.  The second component is the value of
   the artificial variable upon termination of the algorithm.
   The third component is the number of iterations performed in the
   outer loop.

   Derived from: http://www1.american.edu/academic.depts/cas/econ/gaussres/optimize/quadprog.src
   (original GAUSS code by Rob Dittmar <dittmar@stls.frb.org> )

   Lemke's Complementary Pivot algorithm is used here. For a description, see:
   http://ioe.engin.umich.edu/people/fac/books/murty/linear_complementarity_webbook/kat2.pdf

Copyright (c) 2010 Rob Dittmar, Enzo Michelangeli and IT Vision Ltd

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

**Note that:** The below code has been slightly modified to be compatible with the Python version on Google Colab and also to facilitate the desired computations and simulations. \\
Link 1: https://github.com/PythonCharmers/OOSuite/blob/master/OpenOpt/openopt/solvers/HongKongOpt/LCPSolve.py \\
Or \\

Link 2: https://github.com/troyshu/openopt/blob/master/openopt/solvers/HongKongOpt/LCPSolve.py
"""

import numpy as np

def LCPSolve(M, q, pivtol=1e-8, maxits=1e3):
    rayTerm = False
    loopcount = 0

    q = np.asarray(q).flatten()
    dimen = M.shape[0]

    if q.shape[0] != dimen:
        raise ValueError("Matrix M and vector q sizes are incompatible")

    q = q.reshape(-1, 1)  # Ensure q is a column vector (dimen x 1)

    if (q >= 0.).all():  # Check trivial solution: if q >= 0, then w = q and z = 0
        w = q.flatten()  # Flatten the result
        z = np.zeros_like(q).flatten()  # Create a zero array with the same shape as q and flatten it
        retcode = 0.
    else:
        # Create initial tableau
        # Concatenate eye(dimen), -M, -ones((dimen, 1)), and q (already dimen x 1)
        tableau = np.hstack([np.eye(dimen), -M, -np.ones((dimen, 1)), q])

        basis = list(range(dimen))  # basis contains the set of COLUMN indices in the tableau
        locat = np.argmin(tableau[:, 2*dimen+1])  # row of the smallest element in the last column
        basis[locat] = 2*dimen  # replace that choice by artificial variable (column index 2*dimen)
        cand = locat + dimen    # Column index of complement variable for the variable leaving the basis

        # Perform initial pivot step to remove the artificial variable from the basis
        pivot = tableau[locat, :] / tableau[locat, 2*dimen]
        tableau -= tableau[:, 2*dimen:2*dimen+1] * pivot
        tableau[locat, :] = pivot

        # Perform complementary pivot with iteration limit to avoid infinite loops
        oldDivideErr = np.seterr(divide='ignore')['divide']  # suppress divide by zero warnings
        while np.amax(basis) == 2*dimen and loopcount < maxits:
            loopcount += 1
            eMs = tableau[:, cand]  # candidate variable column

            # Mask for elements less than or equal to the pivot tolerance
            missmask = eMs <= 0

            # Compute ratios for pivot selection
            quots = np.full(dimen, np.inf)  # initialize with infinity
            valid_mask = ~missmask & (np.abs(eMs) > pivtol)
            quots[valid_mask] = tableau[valid_mask, 2*dimen+1] / eMs[valid_mask]

            locat = np.argmin(quots)  # position of smallest ratio

            # Check if a valid pivot exists
            if np.isfinite(quots[locat]) and abs(eMs[locat]) > pivtol:
                # Update tableau
                pivot = tableau[locat, :] / tableau[locat, cand]
                tableau -= tableau[:, cand:cand+1] * pivot
                tableau[locat, :] = pivot

                oldVar = basis[locat]  # variable leaving the basis
                basis[locat] = cand    # variable entering the basis

                # Update candidate variable
                if oldVar >= dimen:
                    cand = oldVar - dimen
                else:
                    cand = oldVar + dimen
            else:
                rayTerm = True  # termination due to ray condition (no positive pivot found)
                break
        np.seterr(divide=oldDivideErr)  # restore numpy divide error handling

        # Return solution
        vars = np.zeros(2 * dimen + 1)
        for i, b_idx in enumerate(basis):
            if 0 <= b_idx < len(vars):
                vars[b_idx] = tableau[i, 2*dimen+1]

        w = vars[:dimen].flatten()
        z = vars[dimen:2*dimen].flatten()
        retcode = vars[2*dimen]

    # Return status
    if rayTerm:
        retcode = (2, retcode, loopcount)  # termination due to ray
    else:
        retcode = (1, retcode, loopcount)  # success

    return w, z, retcode